version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - api
